### ISSUE TITLE
Master thesis?

### ISSUE THREAD

**Issue by mstaniak** [FlorianWetschoreck/edaviz#1]
Hi,

I guess this library is related to your master thesis. Could you share the thesis? Unless it isn't finished yet, of course

**Comment by FlorianWetschoreck** [comment]
Hi Mateusz,

thank you for reaching out.
The thesis is under an NDA but if you like we can have a skype call because
I am also very interested in your research.

Please reply to florian.wetschoreck@gmail.com

**Comment by mstaniak** [comment]
Will do, thanks
